### ISSUE TITLE
The range of target Java versions should be specified

### ISSUE THREAD

**Issue by ajnelson-nist** [casework/rdf-toolkit-action#5]
I've encountered some behaviors that might differ in the toolkit between Java versions 11 and 18.

Can this repository's test matrix expand to cover at least those two versions?

I think it would be necessary to test all Python and Java combinations, but if there's no way to do just an "L" of the test matrix, then maybe the matrix should specify Java {11, 18} and Python {3.7, 3.10}.

**Comment by ajnelson-nist** [comment]
Apologies, @kchason , I'd forgotten you'd migrated this to casework.

If you're fine with this being implemented, I'll file a PR.

**Comment by kchason** [comment]
We don't currently have any testing/actions setup, so we'd need to do that first, but that's definitely doable. 

Per GitHub's [documentation](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy), we can have it do all specified combinations if we specify something like:

```yaml
jobs:
  example_matrix:
    strategy:
      matrix:
        java-version: [11, 18]
        python-version: [3.7, "3.10"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
```
